name: Deploy Static Content to Pages

on:
  push:
    branches: ["main"]
 
  workflow_dispatch:

env:
  DEPLOY_TRIGGER_BRANCH: ${{ github.event.inputs.deploy_branch || 'main' }}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-${{ env.DEPLOY_TRIGGER_BRANCH }}"
  cancel-in-progress: true

jobs:
  deploy:
    name: Build & Deploy to Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.DEPLOY_TRIGGER_BRANCH }}
          fetch-depth: 1
          lfs: true
          path: "."

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          cname: ""

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          retry-on-error: true
          retry-delay: 10s
